import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const ecgConductionContent: ExplainerContent = {
  title: 'Every deflection is a wavefront pointing somewhere',
  paragraphs: [
    'An ECG lead records one number: how much of the heart\'s instantaneous electrical vector points along that lead\'s axis. A wavefront travelling toward the positive electrode writes upward, one travelling away writes downward, and one travelling at right angles writes nothing. The trace here is not drawn — it is computed by summing the dipoles of every region that is currently depolarising or repolarising and projecting that sum onto the lead you have selected, which is why the heart diagram and the trace stay exactly in step.',
    'That immediately explains the flat bits, which are the parts students most often misread. The PR segment is isoelectric NOT because nothing is happening — the AV node is conducting hard — but because the node holds far too little tissue to register at the body surface. The ST segment is isoelectric because by then the whole ventricle is uniformly depolarised, so there is no potential DIFFERENCE anywhere to record. Flat line means no net vector, never no activity.',
    'The T wave is the elegant one. Repolarisation is the reverse process, so its current reverses — one sign flip. But the epicardium has a shorter action potential than the endocardium, so it repolarises first and the wavefront travels epicardium-to-endocardium, opposite to the way depolarisation travelled — a second flip. Two flips cancel, so the T wave points the same way as the QRS. That is why a normal T wave is concordant with the QRS in nearly every lead, and it is the reason repolarisation does not simply undo the QRS on paper.',
    'The QT interval is rate-dependent for a physiological reason, not a measurement one. Action potential duration genuinely shortens as heart rate rises — the tissue repolarises faster when it is being driven harder — so a raw QT taken at 100 bpm is not comparable to one taken at 50. Bazett\'s correction exists to undo exactly that, which is why the corrected value is the one that carries meaning. Because the model shortens the action potential with rate rather than simply scaling the trace, the QTc here stays stable while the raw QT moves, which is the behaviour the correction is designed to produce.',
    'Hyperkalaemia is worth watching as three simultaneous effects rather than one sign. Rising potassium peaks the T waves by increasing the amplitude of repolarisation, slows conduction through myocardium so the QRS widens, and depresses atrial excitability until the P wave flattens and eventually disappears. They appear in that rough order as the level climbs, which is why a peaked T is an early warning and a wide QRS without a P is an emergency. Note also what the atria do normally: they have no repolarisation gradient, so unlike the ventricle their Ta wave genuinely does reverse — it is simply small and buried inside the QRS where you never see it.',
    'Switching leads changes nothing about the heart, only your viewing angle — watch the intervals stay identical while the shape transforms. aVR is inverted in a perfectly healthy person because it looks from −150°, nearly opposite the normal mean axis of about +60°; an upright aVR should make you suspect the limb leads are reversed. The same geometry produces reciprocal change: set an inferior injury and the ST elevates in II, III and aVF while simultaneously depressing in aVL, because the identical injury vector projects positively onto one axis and negatively onto the other. Then try a bundle branch block to widen the QRS, complete block to watch the P waves march independently through an escape rhythm, and hyperkalemia to peak the T waves.',
  ],
};
