import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const erythropoiesisContent: ExplainerContent = {
  title: 'The reticulocyte count, not the haemoglobin, tells you why',
  paragraphs: [
    'Erythropoiesis is a slow negative-feedback loop with an unusual sensor. Peritubular cells in the KIDNEY detect tissue oxygen and release erythropoietin, which drives the marrow to make red cells, which carry oxygen, which switches the signal back off. Because the sensor and the hormone are both renal, chronic kidney disease causes anemia through hormone deficiency while the marrow itself remains perfectly capable — which is exactly why recombinant EPO treats it and iron alone does not.',
    'The MCV splits the differential first, and the two common deficiencies push cell size in OPPOSITE directions for a reason worth holding onto. Without iron, haemoglobin accumulates too slowly, so the precursor keeps dividing while it waits to reach its haemoglobin threshold and ends up small — microcytic. Without B12 or folate, DNA synthesis stalls while the cytoplasm matures on schedule, so the cell cannot divide on time and is released oversized — macrocytic. Same organ, same hormone, opposite morphology.',
    'The reticulocyte index then answers the question the haemoglobin cannot: is the marrow actually responding? Below about 2 it is not — a hypoproliferative anemia, where the marrow lacks the signal (renal failure), the raw materials (iron, B12) or the capacity (aplasia). Above it, the marrow is working hard and the problem lies downstream in destruction or loss. Two patients can sit at an identical haemoglobin with completely different diagnoses, and it is this index that separates them.',
    'Compare the presets on EPO as well as on retics and you get the full logic. In aplastic anemia EPO is maximal and the retic index is near zero — the signal is deafening and there is nothing left to answer it. In anemia of CKD the retic index is equally low but the EPO is inappropriately LOW too, because the failing organ is the one that makes it. In haemolysis the retic index climbs above 2: the marrow is doing everything right and the cells are being destroyed faster than it can replace them. And altitude shows the loop working exactly as designed on a person who is not ill at all — low inspired oxygen is sensed as hypoxia at a perfectly normal haemoglobin, and the red cell mass rises until delivery is restored.',
  ],
};
