import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const visionContent: ExplainerContent = {
  title: 'Two receptor systems share one retina, and each owns a different kind of blindness',
  paragraphs: [
    'The retina runs two receptor systems in parallel over a luminance range of about ten billion to one. Cones sit crowded into the fovea, work in daylight, and give you colour and acuity; rods dominate the periphery, work from moonlight down to starlight, and give you sensitivity at the cost of resolution. The two hand over in the mesopic band — dusk, a dim restaurant — where neither is comfortable, and the crossover explains a small library of everyday phenomena. Look slightly beside a faint star and it brightens: you have moved the image off the rod-free fovea onto rod-rich periphery. Your peripheral vision is colourless at night for the same reason.',
    'Transduction runs backwards from what you would design. Light does not excite the photoreceptor; it HYPERpolarises it, closing cGMP-gated sodium channels, and the falling membrane potential reduces glutamate release at the synapse. It is the FALL in glutamate that the ON-bipolar cell reads as light. Watch the glutamate readout as you darken the room: it climbs toward its dark maximum. This sign inversion is not trivia — it is why retinitis pigmentosa can destroy 95 per cent of rods yet spare daylight vision completely, because the cones carry the photopic signal on their own wiring.',
    'Adaptation is the retina moving its operating range to match the background, and it happens on three timescales at once. Cone adaptation follows the scene within seconds; rod dark adaptation has a quick early phase and then a slow one lasting tens of minutes while rhodopsin regenerates. Run a camera flash on the starlight preset and watch brightness collapse: the light is unchanged, but the pigment that reads it has been bleached wholesale, and no amount of wanting will restore sensitivity before the chemistry does. This is also why the pupil reflex tracks raw luminance rather than perceived brightness — long after you feel adapted to a dark cinema your pupils are still wide.',
    'The pupil reflex divides clinically into an afferent limb and an efferent limb, and the division does real diagnostic work. The afferent signal from either eye reaches BOTH Edinger-Westphal nuclei, so direct and consensual responses are equal by construction. Load the optic neuritis preset: the pupils are equal at rest, but shining the torch in the affected eye constricts neither well, because the damaged nerve delivers only a weak signal to both nuclei. That is a relative afferent pupillary defect — the swinging-torch finding. Now load the fixed dilated pupil: here the right efferent supply is gone, so the right pupil stays large whatever you do, yet shining light in EITHER eye constricts the left normally. Afferent lesions make pupils equal and reflexes asymmetric; efferent lesions make pupils unequal and leave the healthy eye untouched.',
    'Acuity belongs almost entirely to cones, which is why it collapses in dim light even in healthy eyes. Under starlight the fovea — packed with cones and starved of rods — contributes essentially nothing, and resolution falls toward the rod periphery ceiling of roughly 6/60. Compare the starlight preset with normal daylight and watch the Snellen denominator climb twenty-fold with nothing whatsoever wrong with the eye. Now load macular degeneration: the scene is bright, the pupils react perfectly, night vision is intact, and yet acuity is 6/36 or worse, because the cone mosaic that performs daylight reading has been lost where it matters most.',
    'The clinical patterns separate cleanly once you ask which system failed and under what lighting. Retinitis pigmentosa is a rod disease: night blindness and peripheral loss, with daylight acuity preserved for years. Macular degeneration is a cone disease: central blur in good light, normal pupillary reflexes, no trouble walking through a dark room. Optic neuritis announces itself on the swinging torch; a surgical third-nerve palsy announces itself as a blown pupil with the other one reacting. The presets are built so those distinctions fall out of the numbers rather than out of memorisation.',
  ],
};
