// Regenerate `src/theme/tokens.generated.ts` from `src/index.css`.
//
// The palette is one of the 16 items in the CLAUDE.md convention list that lives in a CSS file
// the web app loads — and that a React Native app never will. The browser resolves custom
// properties at render time; native has no CSS at all, and tests have no browser. This script
// does the one resolution the browser does — literal hex, a `var()` indirection, or the single
// `color-mix(in oklab, ...)` the dark theme uses to lift all 93 signal colours — and writes the
// result as ordinary static ESM that any bundler understands.
//
// `src/index.css` remains the only source of truth. `src/theme/tokens.generated.test.ts`
// re-parses it and fails if this file has drifted, and it is wired into `npm run verify`, so a
// palette change without regenerating fails before it is pushed. `src/theme/palette.test.ts`
// asserts contrast against the generated output, which is how one calibration serves both
// platforms.
//
//   node tools/generate-tokens/generate.ts
//
// The `.ts` import is Node type stripping (enabled by default since Node 23.6); the imported
// module is erasable-only TS.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colourTokens, parseThemeBlocks, resolveColor } from '../../src/theme/palette.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const cssPath = join(repo, 'src', 'index.css');
const outPath = join(repo, 'src', 'theme', 'tokens.generated.ts');

const blocks = parseThemeBlocks(readFileSync(cssPath, 'utf8'));
const tokens = colourTokens(blocks);

function render(theme) {
  const entries = tokens.map((t) => `    '${t}': '${resolveColor(t, theme, blocks)}',`).join('\n');
  return `  ${theme}: {\n${entries}\n  },`;
}

const source = `/**
 * The colour token palette of src/index.css, resolved to plain hex for both themes.
 *
 * GENERATED by tools/generate-tokens/generate.ts — do not edit. The source of truth is
 * src/index.css; change it there, run node tools/generate-tokens/generate.ts, and
 * npm run verify does that for you. src/theme/tokens.generated.test.ts re-parses the
 * CSS and fails if this file is stale.
 *
 * Every meaningful colour lands here: the surfaces, the text ramp, the brand chrome, the signal
 * bases and all of the dark theme's color-mix(in oklab, ...) lifts, computed exactly as a
 * browser computes them. Non-colour tokens — spacing, radii, type sizes, shadows, wash
 * percentages — have no hex and are deliberately absent.
 *
 * One resolved value per theme in a file both platforms can import is what lets
 * src/theme/palette.test.ts calibrate contrast once for the web and the native app.
 */

export type ThemeName = 'light' | 'dark';

export const TOKENS: Readonly<Record<ThemeName, Readonly<Record<string, string>>>> = {
${render('light')}
${render('dark')}
};
`;

const existing = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;

if (existing === source) {
  console.log(`token palette up to date (${tokens.length} tokens)`);
} else {
  writeFileSync(outPath, source);
  console.log(`token palette written: ${tokens.length} tokens`);
}