import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const respiratoryContent: ExplainerContent = {
  title: 'How breathing and the kidneys defend blood pH',
  paragraphs: [
    'Blood pH is set by the ratio of bicarbonate to dissolved CO2 — the Henderson-Hasselbalch relation, pH = 6.1 + log10(HCO3 / 0.03 x PaCO2). The two terms are controlled by different organs on completely different timescales: the lung sets PaCO2 breath by breath, the kidney sets bicarbonate over days. That division of labour is the reason acid-base disorders are classified as respiratory or metabolic in the first place, and the reason each one has a characteristic compensating partner.',
    'Chemoreceptors sense rising CO2, falling pH, or — only once quite low — falling oxygen, and adjust ventilation within seconds to minutes. This is why Kussmaul breathing appears in DKA: the lungs are compensating for a metabolic acid load, not the primary problem.',
    'Sustained CO2 or pH derangement also triggers slow renal compensation (days): the kidneys generate or excrete bicarbonate to partially normalize pH. This is why chronic COPD can show a near-normal pH despite a persistently high PaCO2, while an acute panic attack’s respiratory alkalosis remains uncompensated.',
    'It is the RATIO that sets the pH, not either number alone, and that single fact explains most acid-base interpretation. A patient can have a grossly abnormal bicarbonate and a grossly abnormal PaCO2 and a pH close to normal, because the two moved together. Compensation works by restoring the ratio while leaving both components deranged — which is why the pH tells you how well-compensated someone is and the individual values tell you what they are compensating FOR. Reading only the pH hides the disorder; reading only the components hides the severity.',
    'Three defences run at completely different speeds, and knowing which one is currently doing the work is most of the clinical reasoning. Chemical buffering is essentially instantaneous. The chemoreceptors adjust ventilation over seconds to minutes. Renal compensation takes days, because it works by generating or excreting bicarbonate rather than by changing anything already in the blood. That ordering is why an acute and a chronic disturbance with identical numbers mean entirely different things, and why the renal arm — which the model lets you switch off — is what separates a compensated chronic picture from an acute crisis.',
    'Oxygen behaves quite differently from CO2, and the dissociation curve is why. Haemoglobin saturation is a sigmoid function of PaO2, not a linear one, so above roughly 60 mmHg the curve is nearly flat — large falls in PaO2 barely move the saturation — while below it the curve turns steeply downward and small further falls cost a great deal. This is why a saturation probe is reassuring across a wide range and then deteriorates abruptly, and why PaO2 and saturation are not interchangeable numbers. Note the model uses a fixed curve, so the Bohr shifts produced by pH, CO2 and temperature are outside its scope.',
  ],
};
