import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const fetalCirculationContent: ExplainerContent = {
  title: 'Two circulations in parallel, and the minute they become one',
  paragraphs: [
    'The fetus oxygenates at the placenta, not the lung, so the whole circulation is built to send blood anywhere EXCEPT the lungs. Fluid-filled, hypoxic lungs present an enormous resistance — many times systemic — so most right ventricular output takes the short cut across the ductus arteriosus into the descending aorta. Watch the pulmonary flow readout in the fetal preset: well under a fifth of output reaches the lungs at all. The two ventricles are not in series as they will be later; they work in parallel into one shared aorta.',
    'Three shunts make that possible, and each has a job. The ductus venosus takes placental blood past the liver. The foramen ovale streams the best-oxygenated blood from the inferior vena cava straight across to the left atrium and out to the head and heart. The ductus arteriosus lets the right ventricle bypass the lungs entirely. Note that even the best fetal blood is only about 80% saturated, and after mixing the fetus runs a pre-ductal saturation in the sixties. That is normal, and an adult with those numbers would be in extremis.',
    'The transition is two events, and the second is the one people forget. The first breath aerates the lung, and both the mechanical opening and the rise in oxygen relax the pulmonary vessels, so pulmonary resistance collapses. At the same moment the cord is clamped — and because the placenta was an enormous low-resistance bed, removing it RAISES systemic resistance sharply. Pulmonary resistance falls while systemic resistance rises, and somewhere in the middle they cross over. Every shunt in the fetal circulation was running on the old gradient.',
    'Once they cross, the shunts close themselves. Pulmonary blood flow floods the left atrium, so left atrial pressure rises above right and the flap of the foramen ovale is simply held shut — functional closure is a pressure event, immediate, long before anything seals anatomically. That is why a probe-patent foramen persists in about a quarter of adults with no consequence at all. The ductus arteriosus constricts in response to the oxygen tension of the blood flowing through it, over hours rather than seconds.',
    'The transition fails in two ways, and they look nothing alike. If the pulmonary vessels will not relax — persistent pulmonary hypertension of the newborn — the fetal gradient survives the birth. The duct stays open, right-to-left shunting continues, and the baby is hypoxic despite a perfectly ventilated lung. Load that preset and look at where the two saturations sit: the right arm is in the nineties while the legs are in the forties. That gap IS the diagnosis, because the shunt enters the aorta below the head and right arm.',
    'The other failure is the same channel carrying flow the other way. A duct that never closes now sits between a high-pressure aorta and a low-pressure pulmonary artery, so it shunts LEFT to right and floods the lungs. Nothing about the duct changed; the pressures either side of it did. And the fact that oxygen closes the duct while prostaglandin holds it open is not merely a curiosity — in a lesion where the systemic circulation depends on ductal flow, a prostaglandin infusion keeps the baby alive until surgery, and giving too much oxygen would close the one channel keeping them perfused.',
  ],
};
