import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const renalTubularContent: ExplainerContent = {
  title: 'How the nephron builds — and then spends — an osmotic gradient',
  paragraphs: [
    'Follow the osmolality along the tubule and the logic falls out. The proximal tubule reabsorbs about two-thirds of the filtered volume ISO-osmotically: a lot of fluid disappears, but its concentration barely changes, so no concentrating work has happened yet. The descending limb is water-permeable and solute-impermeable, so it passively concentrates as water is drawn into the hypertonic medulla. Then the thick ascending limb pumps NaCl out via NKCC2 while staying water-tight, so fluid leaves it HYPOTONIC no matter how concentrated it arrived.',
    'That ascending limb does double duty, and this is the heart of countercurrent multiplication: the salt it deposits in the interstitium is what creates the medullary gradient in the first place, and the descending limb and collecting duct then both depend on that gradient. The loop is quite literally building the tool it later uses.',
    'The collecting duct is the final, ADH-controlled step. Without ADH it stays water-tight and dilute urine pours out; with ADH, aquaporin channels insert and water equilibrates with the medulla. Note the ceiling: however much ADH is present, urine can never become more concentrated than the medullary interstitium — which is why a loop diuretic, by washing out that gradient, blunts concentrating ability even when ADH is given. A thiazide acts further downstream and leaves the gradient intact, which is why it is the milder diuretic.',
    'The osmoreceptor is startlingly steep, and that steepness is the whole reason plasma osmolality is such a stable number. ADH release is essentially silent below threshold and already maximal a mere 18 mOsm/kg above it — a span of a few percent. Everything outside that narrow window is handled by thirst instead. It is worth appreciating what this buys: a person can drink four litres in an evening or none all day, and the osmolality the cells actually experience barely moves.',
    'It helps to read the nephron as a pipeline rather than a store. Each segment is a pure consequence of what entered it, the current medullary gradient, and whatever hormones and drugs are acting — the tubule itself holds nothing between beats. Only the plasma, the medulla and the hormone levels carry state. That is why the whole osmolality profile can be recomputed from scratch each moment, and why following a single bolus of filtrate down the diagram tells you everything the kidney is doing to it.',
    'Central and nephrogenic diabetes insipidus look identical at the bedside — dilute urine, rising plasma osmolality, unquenchable thirst — and the model shows why they are nonetheless easy to separate. In central DI, ADH is simply absent; in nephrogenic DI, ADH is maximal but the duct cannot respond. Give desmopressin and the two diverge instantly: central DI concentrates its urine sharply, nephrogenic DI barely moves. Meanwhile tubuloglomerular feedback runs quietly underneath all of this, with the macula densa sensing NaCl delivery and constricting the afferent arteriole to protect the nephron from over-filtering.',
  ],
};
