import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const immuneResponseContent: ExplainerContent = {
  title: 'Why the second exposure is nothing like the first',
  paragraphs: [
    'A primary response is slow for a structural reason. Innate immunity — neutrophils, macrophages, complement — is active within hours, but it is fixed and non-specific, and it can only slow an organism down, not clear it. Meanwhile dendritic cells must sample antigen, migrate to a lymph node, and find the one naive lymphocyte in millions that happens to recognise it. That search takes days, and the pathogen is replicating exponentially throughout. Almost everything that makes a first infection an illness happens during that delay.',
    'Helper T cells are the hub the whole adaptive system turns on. They license cytotoxic T cells to kill infected cells, and they supply the second signal B cells need to switch class from IgM to the far more potent IgG. Because one cell type gates both arms, losing it takes out cellular and humoral immunity simultaneously — which is exactly why CD4 count predicts opportunistic infection in HIV so well. Compare the HIV preset with the B-cell deficiency preset and watch the difference: the B-cell defect leaves cytotoxic killing perfectly intact, whereas CD4 depletion flattens both.',
    'Which arm actually matters depends on where the organism hides. Antibody neutralises pathogens in the extracellular space but cannot reach inside a host cell, so an intracellular organism has to be dealt with by cytotoxic T cells killing the infected cell itself. Switch the pathogen type and you change which deficiency is dangerous, not merely how sick the host gets.',
    'Memory is the payoff, and here it emerges from the model rather than being scripted. Surviving an infection leaves a persistent population of memory cells, which does two things: it removes the search delay, and it raises the number of antigen-specific precursors so the response is bigger as well as faster. Clear an infection, then infect the same host again — the organism barely grows before it is met, clearance takes a fraction as long, and there is essentially no fever. Vaccination reaches the identical end state by a shorter road: antigen without a replicating organism, so memory forms and the host is never ill at all.',
  ],
};
