import type { ExplainerContent } from '@/shared/components/ExplainerPanel/ExplainerPanel';

export const respiratoryMechanicsContent: ExplainerContent = {
  title: 'Reading spirometry, and why shunt and dead space are not the same problem',
  paragraphs: [
    'Compliance and resistance are independent properties, and they fail in opposite directions. Low compliance means a stiff lung that cannot be inflated far, so vital capacity falls — but it empties perfectly well, which is why the FEV1/FVC ratio stays normal or even rises. High resistance means a lung that fills normally but empties slowly, so the ratio collapses while vital capacity is broadly preserved. That single contrast — reduced FVC with a preserved ratio versus a reduced ratio — is how restrictive and obstructive patterns are told apart.',
    'The R × C time constant explains air trapping. Expiration is passive and exponential, needing roughly three time constants to finish. Raise resistance and the lung needs longer; if the next breath arrives before emptying completes, volume stacks up breath after breath. This is why residual volume and FRC RISE in obstruction (hyperinflation), and why breathing faster makes an obstructed patient worse rather than better — the treatment for dynamic hyperinflation is to slow the rate and lengthen expiration.',
    'Surfactant is a separate route to a stiff lung. By Laplace\'s law (P = 2T/r), surface tension generates more collapsing pressure in smaller alveoli, so without surfactant small alveoli would empty into large ones. Surfactant\'s tension-lowering effect is strongest at small radii, which stabilizes alveoli against each other. Losing it — as in neonatal respiratory distress syndrome — produces restriction by a mechanism entirely distinct from fibrotic tissue stiffening.',
    'Dead space and shunt are both "V/Q mismatch" but behave oppositely, and only one has a defence. Dead space is ventilated but not perfused (V/Q → infinity), as in pulmonary embolism. Shunt is perfused but not ventilated (V/Q → 0), as in pneumonia or atelectasis. Hypoxic pulmonary vasoconstriction senses low alveolar oxygen and diverts blood away from poorly ventilated lung — which partially rescues a shunt. Against dead space it is completely powerless: there is no perfusion left in that unit to redirect. Set a shunt and watch HPV engage; set an equivalent dead space and watch it do nothing at all.',
  ],
};
