// Regenerate `src/modules/manifest.generated.ts` from the module directories.
//
// This replaces the `import.meta.glob` calls that `home/moduleQuestionIds.ts` and
// `shared/chat/corpus.ts` used to discover modules with. The glob was the right answer while
// Vite was the only bundler: module ids already appear in four places (see CLAUDE.md) and a
// fifth hand-maintained list that silently under-reports would be the least visible of them.
//
// Metro has no equivalent and Hermes rejects `import.meta` at compile time, so the React Native
// app cannot load either file. A GENERATED list keeps the property the glob was chosen for —
// nobody maintains it by hand — while being ordinary static ESM that any bundler understands.
// `src/modules/manifest.generated.test.ts` re-globs and fails if this file has drifted, so the
// generated list cannot quietly stop covering a module.
//
//   node tools/module-manifest/generate.mjs
//
// Wired into `npm run verify`, so a module added without regenerating fails before it is pushed.

import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const modulesDir = join(repo, 'src', 'modules');
const outPath = join(modulesDir, 'manifest.generated.ts');

/** Every directory under src/modules that carries both of the files we index. */
function discover() {
  return readdirSync(modulesDir)
    .filter((name) => statSync(join(modulesDir, name)).isDirectory())
    .filter(
      (name) =>
        existsSync(join(modulesDir, name, 'questions.ts')) &&
        existsSync(join(modulesDir, name, 'content.ts')),
    )
    .sort();
}

function render(ids) {
  const entries = (file) => ids.map((id) => `  ${id}: () => import('./${id}/${file}'),`).join('\n');

  return `/**
 * Every module directory, as static imports.
 *
 * GENERATED by \`tools/module-manifest/generate.mjs\` — do not edit. Run
 * \`node tools/module-manifest/generate.mjs\` after adding or removing a module;
 * \`npm run verify\` does it for you and \`manifest.generated.test.ts\` fails if it is stale.
 *
 * Keyed by module id, which IS the directory name (CLAUDE.md, "Conventions"). Both consumers —
 * \`home/moduleQuestionIds.ts\` and \`shared/chat/corpus.ts\` — used to parse that id back out of a
 * glob key, so keying by it here removes a regex from each of them.
 *
 * The loaders are deliberately lazy, for the reason \`moduleQuestionIds.ts\` documents at length:
 * eagerly importing these welds every module's questions and ~105,000 words of explainer prose
 * into whichever chunk imports this file. Vite code-splits a static \`import()\` at least as well
 * as it did the glob, and Metro handles it natively.
 */

export type ModuleLoader = () => Promise<Record<string, unknown>>;

/** Module ids in directory order, which is alphabetical. */
export const MODULE_IDS: readonly string[] = [
${ids.map((id) => `  '${id}',`).join('\n')}
];

export const questionModules: Readonly<Record<string, ModuleLoader>> = {
${entries('questions')}
};

export const contentModules: Readonly<Record<string, ModuleLoader>> = {
${entries('content')}
};
`;
}

const ids = discover();
const source = render(ids);
const existing = existsSync(outPath) ? readFileSync(outPath, 'utf8') : null;

if (existing === source) {
  console.log(`module manifest up to date (${ids.length} modules)`);
} else {
  writeFileSync(outPath, source);
  console.log(`module manifest written: ${ids.length} modules`);
}
